### ISSUE TITLE
схемy сделать  доступной нa easyeda.com

### ISSUE THREAD

**Issue by Egyras** [pruwait/Nice_BusT4#1]
Здравствуй, может ты сможешь схемy сделать  доступной нa easyeda.com ? Вставь ссылку в README.md.

**Comment by ashumkin** [comment]
плюсую

**Comment by pruwait** [comment]
Схема выложена как картинка. Срисовать ее в easyeda сможет каждый за полчаса, там всего 2 микросборки и немного обвязки. Моя схема задействована в крупном проекте, который я не буду выкладывать.
