### ISSUE TITLE
Vsb is not always 24V

### ISSUE THREAD

**Issue by xdanik** [pruwait/Nice_BusT4#4]
As the title says - Vsb (power provided from the Nice motor) is not always 24V DC.

I have a Nice Road 400 with RBA4R10 control unit and I have measured 34V between the Vsb and GND pins.
This would certainly kill the Wemos D1 power shield as its rated for 24V max.
I was lucky to measure it before connecting it 😉.

When you look at the [schematics for IBT4N](https://github.com/pruwait/Nice_BusT4/blob/078a50ae64e9510a1a09f8f559e44e69ae7ddb0c/Nice%20IBT4N.pdf) there is a U1 - 78L05 linear voltage regulator powered by the Vsb line that is rated for up to 35V.

It would be great to mention this in the readme.

**Comment by pruwait** [comment]
Yep. Its Nice joke. 24V is 34V for all devices.
My Wemos D1 power shield is working good with 34V. But it was a prototip.
Device 2.0 has power unit with XL1509 with wide 4.5V to 40V Input Voltage Range.
