### ISSUE TITLE
Translate to English?

### ISSUE THREAD

**Issue by xdanik** [pruwait/Nice_BusT4#5]
In order to better understand the readme/comments I have created [a fork of this repo](https://github.com/xdanik/Nice_BusT4) and let it translate to English.
Its very rough translation as I do not speak Russian - it was translated by Google Translate.

IMHO this project could be very useful for peoples outside Russian speaking countries. Nice is Italian company and its widespreadly used in Europe.

Would you be willing to translate this project to English (or merging my changes)?

**Comment by pruwait** [comment]
I added link to your fork in readme.

Whats about comments? I writing comments for myself. Code is very simple and comments need me cause my skill is low. 
Good programmer no needs my comments).
