### ISSUE TITLE
Hardware needed

### ISSUE THREAD

**Issue by rici44** [pruwait/Nice_BusT4#8]
Hi there. I would like to ask what type of hardware exactly do I need to setup Nice_BusT4? I understand that I need Wemos D1 mini with Power shield but do not know what else. Thank you.

**Comment by ekozan** [comment]
Check the schematic you
Need to solder or find some look like card

**Comment by pruwait** [comment]
> Hi there. Do you have EasyEda project published? I would like to order this adapter.

Gerber files from easyeda is present in my project
